import type { SeedWord } from "./initial-vocab";

export const FOUNDATION_VOCAB_1: SeedWord[] = [
  { lemma: "и", translation: "And, though" },
  { lemma: "в", translation: "in, at" },
  { lemma: "не", translation: "Not" },
  { lemma: "он", translation: "he" },
  { lemma: "на", translation: "on, it, at, to" },
  { lemma: "я", translation: "I" },
  { lemma: "что", translation: "what, that, why" },
  { lemma: "тот", translation: "that" },
  { lemma: "быть", translation: "to be" },
  { lemma: "с", translation: "with, and, from, of" },
  { lemma: "а", translation: "while, and, but" },
  { lemma: "весь", translation: "all, everything" },
  { lemma: "это", translation: "that, this, it" },
  { lemma: "как", translation: "how, what, as, like" },
  { lemma: "она", translation: "she" },
  { lemma: "по", translation: "on, along, by" },
  { lemma: "но", translation: "but" },
  { lemma: "они", translation: "they" },
  { lemma: "к", translation: "to, for, by" },
  { lemma: "у", translation: "by, with, of" },
  { lemma: "ты", translation: "you, thou" },
  { lemma: "из", translation: "from, of, in" },
  { lemma: "мы", translation: "we" },
  { lemma: "за", translation: "behind, over, at, after" },
  { lemma: "вы", translation: "you (formal), you (plural)" },
  { lemma: "так", translation: "so, thus, then" },
  { lemma: "же", translation: "and, as for, but, same" },
  { lemma: "от", translation: "from, of, for" },
  { lemma: "сказать", translation: "to say, to speak" },
  { lemma: "этот", translation: "this" },
  { lemma: "который", translation: "which, who, that" },
  { lemma: "мочь", translation: "to be able" },
  { lemma: "человек", translation: "man, person" },
  { lemma: "о", translation: "of, about, against" },
  { lemma: "один", translation: "one, some, alone" },
  { lemma: "ещё", translation: "still, yet" },
  { lemma: "бы", translation: "would" },
  { lemma: "такой", translation: "such, so, some" },
  { lemma: "только", translation: "only, merely, but" },
  { lemma: "себя", translation: "myself, himself, herself" },
  { lemma: "своё", translation: "one's own, my, our" },
  { lemma: "какой", translation: "what, which, how" },
  { lemma: "когда", translation: "when, while, as" },
  { lemma: "уже", translation: "already, by now" },
  { lemma: "для", translation: "for, to" },
  { lemma: "вот", translation: "here, there, this is, that's" },
  { lemma: "кто", translation: "who, that, some" },
  { lemma: "да", translation: "yes, but" },
  { lemma: "говорить", translation: "to say, to tell, to speak" },
  { lemma: "год", translation: "year" },
  { lemma: "знать", translation: "to know, to be aware" },
  { lemma: "мой", translation: "my, mine" },
  { lemma: "до", translation: "to, up to, about, before" },
  { lemma: "или", translation: "or" },
  { lemma: "если", translation: "if" },
  { lemma: "время", translation: "time, season" },
  { lemma: "рука", translation: "hand, arm" },
  { lemma: "нет", translation: "no, not, but" },
  { lemma: "самый", translation: "most, the very, the same" },
  { lemma: "ни", translation: "not a, not, neither … nor" },
  { lemma: "стать", translation: "to become, to begin, to come" },
  { lemma: "большой", translation: "big, large, important" },
  { lemma: "даже", translation: "even" },
  { lemma: "другой", translation: "other, another, different" },
  { lemma: "наш", translation: "our, ours" },
  { lemma: "свой", translation: "my, our, your" },
  { lemma: "ну", translation: "now, right, well, come on" },
  { lemma: "под", translation: "under, for, towards, to" },
  { lemma: "где", translation: "where" },
  { lemma: "дело", translation: "business, affair, matter" },
  { lemma: "есть", translation: "to eat, to be" },
  { lemma: "сам", translation: "myself, yourself" },
  { lemma: "раз", translation: "time, once, since" },
  { lemma: "чтобы", translation: "that, in order that" },
  { lemma: "два", translation: "two" },
  { lemma: "там", translation: "there, then" },
  { lemma: "чем", translation: "than, instead of" },
  { lemma: "глаз", translation: "eye, sight" },
  { lemma: "жизнь", translation: "life" },
  { lemma: "первый", translation: "first, front, former" },
  { lemma: "день", translation: "day" },
  { lemma: "тут", translation: "here, now, then" },
  { lemma: "во", translation: "in, at; super, exactly" },
  { lemma: "ничто", translation: "nothing" },
  { lemma: "потом", translation: "afterwards, then" },
  { lemma: "очень", translation: "very" },
  { lemma: "со", translation: "with" },
  { lemma: "хотеть", translation: "to want, to like" },
  { lemma: "ли", translation: "whether, if" },
  { lemma: "при", translation: "attached to, in the presence of, by, about" },
  { lemma: "голова", translation: "head, mind, brains" },
  { lemma: "надо", translation: "over, above, ought to" },
  { lemma: "без", translation: "without" },
  { lemma: "видеть", translation: "to see" },
  { lemma: "идти", translation: "to go, to come" },
  { lemma: "теперь", translation: "now, nowadays" },
  { lemma: "тоже", translation: "also, as well, too" },
  { lemma: "стоять", translation: "to stand, to be, to stand up" },
  { lemma: "друг", translation: "friend" },
  { lemma: "дом", translation: "house, home" },
  { lemma: "сейчас", translation: "now, presently, soon" },
  { lemma: "можно", translation: "one can" },
  { lemma: "после", translation: "after, afterwards" },
  { lemma: "слово", translation: "word" },
  { lemma: "здесь", translation: "here" },
  { lemma: "думать", translation: "to think, to believe" },
  { lemma: "место", translation: "place, seat" },
  { lemma: "спросить", translation: "to ask" },
  { lemma: "через", translation: "through, across" },
  { lemma: "лицо", translation: "face, person" },
  { lemma: "тогда", translation: "then" },
  { lemma: "ведь", translation: "you see, you know" },
  { lemma: "хороший", translation: "good, nice" },
  { lemma: "каждый", translation: "each, every" },
  { lemma: "новый", translation: "new, modern" },
  { lemma: "жить", translation: "to live" },
  { lemma: "должный", translation: "due, proper" },
  { lemma: "смотреть", translation: "to look, to watch" },
  { lemma: "почему", translation: "why" },
  { lemma: "потому", translation: "that's why" },
  { lemma: "сторона", translation: "side, party" },
  { lemma: "просто", translation: "simply" },
  { lemma: "нога", translation: "foot, leg" },
  { lemma: "сидеть", translation: "to sit" },
  { lemma: "понять", translation: "to understand, to realize" },
  { lemma: "иметь", translation: "to have, to own" },
  { lemma: "конечный", translation: "final, last" },
  { lemma: "делать", translation: "to do, to make" },
  { lemma: "вдруг", translation: "suddenly" },
  { lemma: "над", translation: "above, over" },
  { lemma: "взять", translation: "to take" },
  { lemma: "никто", translation: "nobody" },
  { lemma: "сделать", translation: "to do, to make, to finish" },
  { lemma: "дверь", translation: "door" },
  { lemma: "перед", translation: "before, in front of" },
  { lemma: "нужный", translation: "necessary" },
  { lemma: "понимать", translation: "to understand" },
  { lemma: "казаться", translation: "to seem, to appear" },
  { lemma: "работа", translation: "work, job" },
  { lemma: "три", translation: "three" },
  { lemma: "ваш", translation: "yours" },
  { lemma: "уж", translation: "really, already" },
  { lemma: "земля", translation: "earth, land, soil" },
  { lemma: "конец", translation: "end, distance" },
  { lemma: "несколько", translation: "several, some" },
  { lemma: "час", translation: "hour, time" },
  { lemma: "голос", translation: "voice" },
  { lemma: "город", translation: "town, city" },
  { lemma: "последний", translation: "last, the latest, new" },
  { lemma: "пока", translation: "for the present" },
  { lemma: "хорошо", translation: "well" },
  { lemma: "давать", translation: "to give, to let, to allow" },
  { lemma: "вода", translation: "water" },
  { lemma: "более", translation: "more" },
  { lemma: "хотя", translation: "although" },
  { lemma: "всегда", translation: "always" },
  { lemma: "второй", translation: "second" },
  { lemma: "куда", translation: "where, what for, much" },
  { lemma: "пойти", translation: "to go by foot, to walk" },
  { lemma: "стол", translation: "table, desk, board" },
  { lemma: "ребёнок", translation: "child, kid, infant" },
  { lemma: "увидеть", translation: "to see" },
  { lemma: "сила", translation: "strength, force" },
  { lemma: "отец", translation: "father" },
  { lemma: "женщина", translation: "woman" },
  { lemma: "машина", translation: "car, machine, engine" },
  { lemma: "случай", translation: "case, occasion, incident" },
  { lemma: "ночь", translation: "night" },
  { lemma: "сразу", translation: "at once, right away, just" },
  { lemma: "мир", translation: "world, peace" },
  { lemma: "совсем", translation: "quite, entirely, totally" },
  { lemma: "остаться", translation: "to remain, to stay" },
  { lemma: "об", translation: "about, of" },
  { lemma: "вид", translation: "appearance, look, view" },
  { lemma: "выйти", translation: "to go out, to come out, to appear" },
  { lemma: "дать", translation: "to give" },
  { lemma: "работать", translation: "to work" },
  { lemma: "любить", translation: "to love" },
  { lemma: "старый", translation: "old" },
  { lemma: "почти", translation: "almost" },
  { lemma: "ряд", translation: "row, line" },
  { lemma: "оказаться", translation: "find oneself, turn out" },
  { lemma: "начало", translation: "beginning, origin, source" },
  { lemma: "твой", translation: "your, yours" },
  { lemma: "вопрос", translation: "question, matter, problem" },
  { lemma: "много", translation: "many, much" },
  { lemma: "война", translation: "war" },
  { lemma: "снова", translation: "again" },
  { lemma: "ответить", translation: "to answer, to reply" },
  { lemma: "между", translation: "between, among" },
  { lemma: "подумать", translation: "to think" },
  { lemma: "опять", translation: "again" },
  { lemma: "белый", translation: "white" },
  { lemma: "деньги", translation: "money" },
  { lemma: "значить", translation: "to mean, to signify" },
  { lemma: "про", translation: "about, for" },
  { lemma: "лишь", translation: "only, as soon as" },
  { lemma: "минута", translation: "minute, moment" },
  { lemma: "жена", translation: "wife" },
];
