export interface SeedWord {
  lemma: string;
  translation: string;
}

export const INITIAL_VOCAB: SeedWord[] = [
  { lemma: "я", translation: "I" },
  { lemma: "думать", translation: "to think" },
  { lemma: "вы", translation: "you (plural/formal)" },
  { lemma: "слышать", translation: "to hear" },
  { lemma: "о", translation: "about" },
  { lemma: "принцип", translation: "principle" },
  { lemma: "закон", translation: "law" },
  { lemma: "его", translation: "his/it" },
  { lemma: "ещё", translation: "still/yet" },
  { lemma: "называть", translation: "to call" },
  { lemma: "он", translation: "he" },
  { lemma: "говорить", translation: "to speak" },
  { lemma: "что", translation: "that/what" },
  { lemma: "усилия", translation: "efforts" },
  { lemma: "давать", translation: "to give" },
  { lemma: "результат", translation: "result" },
  { lemma: "и", translation: "and" },
  { lemma: "наоборот", translation: "on the contrary" },
  { lemma: "только", translation: "only" },
  { lemma: "мочь", translation: "to be able to" },
  { lemma: "встретить", translation: "to meet/encounter" },
  { lemma: "эффект", translation: "effect" },
  { lemma: "этого", translation: "this (genitive)" },
  { lemma: "везде", translation: "everywhere" },
  { lemma: "в", translation: "in" },
  { lemma: "спорт", translation: "sport" },
  { lemma: "бизнес", translation: "business" },
  { lemma: "психология", translation: "psychology" },
  { lemma: "отношения", translation: "relationships" },
  { lemma: "конечно", translation: "of course" },
  { lemma: "изучение", translation: "study" },
  { lemma: "язык", translation: "language" },
  { lemma: "знать", translation: "to know" },
  { lemma: "выучить", translation: "to learn" },
  { lemma: "ситуация", translation: "situation" },
  { lemma: "или", translation: "or" },
  { lemma: "грамматика", translation: "grammar" },
  { lemma: "использовать", translation: "to use" },
  { lemma: "цифра", translation: "digit/number" },
  { lemma: "условный", translation: "conditional" },
  { lemma: "точный", translation: "exact" },
  { lemma: "понимать", translation: "to understand" },
  { lemma: "логика", translation: "logic" },
  { lemma: "сегодня", translation: "today" },
  { lemma: "видео", translation: "video" },
  { lemma: "будем", translation: "we will (be)" },
  { lemma: "применить", translation: "to apply" },
  { lemma: "разговорный", translation: "conversational" },
  { lemma: "речь", translation: "speech" },
  { lemma: "какой", translation: "which" },
  { lemma: "тема", translation: "topic" },
  { lemma: "нам", translation: "to us" },
  { lemma: "нужно", translation: "necessary" },
  { lemma: "тренировать", translation: "to train" },
  { lemma: "чувствовать себя", translation: "to feel" },
  { lemma: "комфортно", translation: "comfortably" },
  { lemma: "уверенно", translation: "confidently" },
  { lemma: "мы", translation: "we" },
  { lemma: "русский", translation: "Russian" },
  { lemma: "даже", translation: "even" },
  { lemma: "нет", translation: "no/not" },
  { lemma: "такой", translation: "such" },
  { lemma: "слово", translation: "word" },
  { lemma: "выражение", translation: "expression" },
  { lemma: "ни о чём", translation: "about nothing" },
  { lemma: "повседневный", translation: "everyday" },
  { lemma: "общий", translation: "general" },
  { lemma: "если", translation: "if" },
  { lemma: "лучший", translation: "best" },
  { lemma: "эквивалент", translation: "equivalent" },
  { lemma: "перевод", translation: "translation" },
  { lemma: "сказать", translation: "to say" },
  { lemma: "пожалуйста", translation: "please" },
  { lemma: "комментарий", translation: "comment" },
  { lemma: "но", translation: "but" },
  { lemma: "в любом случае", translation: "in any case" },
  { lemma: "разбирать", translation: "to analyze" },
  { lemma: "самый", translation: "the most" },
  { lemma: "частый", translation: "frequent" },
  { lemma: "популярный", translation: "popular" },
  { lemma: "распространенный", translation: "common" },
  { lemma: "совершенствовать", translation: "to perfect" },
  { lemma: "перед", translation: "before" },
  { lemma: "тем", translation: "that (instrumental)" },
  { lemma: "как", translation: "how/like" },
  { lemma: "начинать", translation: "to begin" },
  { lemma: "хотеть", translation: "to want" },
  { lemma: "рада", translation: "glad (fem)" },
  { lemma: "видеть", translation: "to see" },
  { lemma: "канал", translation: "channel" },
  { lemma: "первый", translation: "first" },
  { lemma: "раз", translation: "time/instance" },
  { lemma: "добро пожаловать", translation: "welcome" },
  { lemma: "дружный", translation: "friendly" },
  { lemma: "компания", translation: "company/group" },
  { lemma: "уже", translation: "already" },
  { lemma: "смотреть", translation: "to watch" },
  { lemma: "снова", translation: "again" },
  { lemma: "надеяться", translation: "to hope" },
  { lemma: "настроение", translation: "mood" },
  { lemma: "не", translation: "not" },
  { lemma: "забыть", translation: "to forget" },
  { lemma: "поставить лайк", translation: "to like" },
  { lemma: "нравиться", translation: "to like" },
  { lemma: "подписаться", translation: "to subscribe" },
  { lemma: "потому что", translation: "because" },
  { lemma: "впереди", translation: "ahead" },
  { lemma: "много", translation: "many/much" },
  { lemma: "интересный", translation: "interesting" },
  { lemma: "всё", translation: "all/everything" },
  { lemma: "сейчас", translation: "now" },
  { lemma: "готовый", translation: "ready" },
  { lemma: "адекватный", translation: "adequate" },
  { lemma: "термин", translation: "term" },
  { lemma: "культура", translation: "culture" },
  { lemma: "никто", translation: "no one" },
  { lemma: "спрашивать", translation: "to ask" },
  { lemma: "лифт", translation: "elevator" },
  { lemma: "сосед", translation: "neighbor" },
  { lemma: "продавец", translation: "salesperson" },
  { lemma: "супермаркет", translation: "supermarket" },
  { lemma: "потому", translation: "because" },
  { lemma: "недружелюбный", translation: "unfriendly" },
  { lemma: "необщительный", translation: "unsociable" },
  { lemma: "дружелюбный", translation: "friendly" },
  { lemma: "общительный", translation: "sociable" },
  { lemma: "контекст", translation: "context" },
  { lemma: "знакомые", translation: "acquaintances" },
  { lemma: "приятель", translation: "buddy" },
  { lemma: "друг", translation: "friend" },
  { lemma: "близкий", translation: "close" },
  { lemma: "ожидать", translation: "to expect" },
  { lemma: "глубокий", translation: "deep" },
  { lemma: "поверхностный", translation: "superficial" },
  { lemma: "обсудить", translation: "to discuss" },
  { lemma: "рамки", translation: "frameworks" },
  { lemma: "погода", translation: "weather" },
  { lemma: "структура", translation: "structure" },
  { lemma: "собственно", translation: "actually" },
  { lemma: "предлагать", translation: "to suggest" },
  { lemma: "подумать", translation: "to think a bit" },
  { lemma: "родственники", translation: "relatives" },
  { lemma: "телефон", translation: "telephone" },
  { lemma: "легко", translation: "easily" },
  { lemma: "быстро", translation: "quickly" },
  { lemma: "поддерживать", translation: "to maintain" },
  { lemma: "беседа", translation: "conversation" },
  { lemma: "универсальный", translation: "universal" },
  { lemma: "порядок", translation: "order" },
  { lemma: "актуальный", translation: "relevant" },
  { lemma: "записывать", translation: "to write down" },
  { lemma: "мнение", translation: "opinion" },
  { lemma: "происходить", translation: "to happen" },
  { lemma: "окно", translation: "window" },
  { lemma: "улица", translation: "street" },
  { lemma: "студент", translation: "student" },
  { lemma: "равнодушный", translation: "indifferent" },
  { lemma: "тепло", translation: "warm" },
  { lemma: "холодно", translation: "cold" },
  { lemma: "регулярно", translation: "regularly" },
  { lemma: "время", translation: "time" },
  { lemma: "огромный", translation: "huge" },
  { lemma: "запас", translation: "supply" },
  { lemma: "жарко", translation: "hot" },
  { lemma: "оттенок", translation: "shade" },
  { lemma: "прохладно", translation: "cool" },
  { lemma: "ветрено", translation: "windy" },
  { lemma: "метель", translation: "blizzard" },
  { lemma: "вьюга", translation: "snowstorm" },
  { lemma: "ливень", translation: "downpour" },
  { lemma: "град", translation: "hail" },
  { lemma: "гроза", translation: "thunderstorm" },
  { lemma: "мокрый", translation: "wet" },
  { lemma: "снег", translation: "snow" },
  { lemma: "нюанс", translation: "nuance" },
  { lemma: "чувствовать", translation: "to feel" },
  { lemma: "вежливость", translation: "politeness" },
  { lemma: "может", translation: "maybe" },
  { lemma: "задумываться", translation: "to ponder" },
  { lemma: "жаловаться", translation: "to complain" },
  { lemma: "загруженный", translation: "busy" },
  { lemma: "день", translation: "day" },
  { lemma: "устать", translation: "to get tired" },
  { lemma: "собака", translation: "dog" },
  { lemma: "спринт", translation: "sprint" },
  { lemma: "эмоции", translation: "emotions" },
  { lemma: "работа", translation: "work" },
  { lemma: "учёба", translation: "study" },
  { lemma: "успевать", translation: "to manage" },
  { lemma: "пространство", translation: "space" },
  { lemma: "вариант", translation: "option" },
  { lemma: "завал", translation: "pile-up" },
  { lemma: "спокойный", translation: "calm" },
  { lemma: "планы", translation: "plans" },
  { lemma: "выходные", translation: "weekend" },
  { lemma: "планировать", translation: "to plan" },
  { lemma: "отпуск", translation: "vacation" },
  { lemma: "занят", translation: "busy" },
  { lemma: "приблизительно", translation: "approximately" },
  { lemma: "шанс", translation: "chance" },
  { lemma: "возможность", translation: "opportunity" },
  { lemma: "исследуя", translation: "exploring" },
  { lemma: "встречаться", translation: "to meet up" },
  { lemma: "кино", translation: "cinema" },
  { lemma: "музей", translation: "museum" },
  { lemma: "сериал", translation: "series" },
  { lemma: "играть", translation: "to play" },
  { lemma: "активность", translation: "activity" },
  { lemma: "сопровождать", translation: "to accompany" },
  { lemma: "здоровье", translation: "health" },
  { lemma: "самочувствие", translation: "well-being" },
  { lemma: "побаливать", translation: "to ache slightly" },
  { lemma: "спина", translation: "back" },
  { lemma: "лежать", translation: "to lie down" },
  { lemma: "еда", translation: "food" },
  { lemma: "напитки", translation: "drinks" },
  { lemma: "рекомендации", translation: "recommendations" },
  { lemma: "советовать", translation: "to advise" },
  { lemma: "ресторан", translation: "restaurant" },
  { lemma: "ужин", translation: "dinner" },
  { lemma: "путешествия", translation: "travels" },
  { lemma: "город", translation: "city" },
  { lemma: "откуда", translation: "from where" },
  { lemma: "переезжать", translation: "to move house" },
  { lemma: "глагол", translation: "verb" },
  { lemma: "приставка", translation: "prefix" },
  { lemma: "проблема", translation: "problem" },
  { lemma: "хобби", translation: "hobby" },
  { lemma: "отдых", translation: "rest" },
  { lemma: "увлекаться", translation: "to be into" },
  { lemma: "шахматы", translation: "chess" },
  { lemma: "кулинария", translation: "cooking" },
  { lemma: "музыка", translation: "music" },
  { lemma: "транскрипт", translation: "transcript" },
  { lemma: "интеллект", translation: "intelligence" },
  { lemma: "пересказывать", translation: "to retell" },
  { lemma: "фильмы", translation: "movies" },
  { lemma: "концерт", translation: "concert" },
  { lemma: "семья", translation: "family" },
  { lemma: "дети", translation: "children" },
  { lemma: "история", translation: "story" },
  { lemma: "новости", translation: "news" },
  { lemma: "бездонная", translation: "bottomless" },
  { lemma: "спонтанный", translation: "spontaneous" },
];
